### ISSUE TITLE
Arquivos duplicados

### ISSUE THREAD

**Issue by ajtga** [flow-ufal/meninas#11]
Me parece que os arquivos`views.py` e `urls.py` no [diretório raiz](https://github.com/flow-ufal/meninas) do projeto são duplicatas. @lucasuchoa98 os adicionou [neste commit](https://github.com/flow-ufal/meninas/commit/80599a5c2be3fd72c6ef3a9d375e2d04fdb45bfe).

**Comment by MateusMNormande** [comment]
Removi da _branch_.

**Comment by ajtga** [comment]
@MateusMNormande, boa! Agora faltou remover da `master` também, pois quando o PR for mesclado os arquivos duplicados continuaram nela.
